docker:
  image: yegor256/rultor-image:1.13.0
readers:
  - "urn:github:526301"
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/rultor/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  heroku-netrc: yegor256/home#assets/heroku-netrc
install: |-
  pdd --file=/dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
merge:
  script: |-
    mvn help:system clean install -Pqulice -Prultor --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml --quiet
release:
  pre: false
  sensitive:
    - settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    echo "Author of the request: ${author}"
    mvn versions:set "-DnewVersion=${tag}" --quiet
    git commit -am "${tag}"
    cp ../settings.xml settings.xml
    mvn clean package -Pqulice -Prultor --errors --batch-mode --quiet
    git remote add heroku https://git.heroku.com/rultor.git
    mv ../heroku-netrc ~/.netrc
    build=$(git rev-parse --short HEAD)
    sed -i "s/BUILD/${build}/g" src/main/resources/META-INF/MANIFEST.MF
    git add src/main/resources/META-INF/MANIFEST.MF
    git add src/main/resources/log4j.properties
    git commit -m 'build number set'
    git add settings.xml
    git commit -m 'settings.xml'
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -rf settings.xml
    curl --insecure -f --connect-timeout 30 --retry 8 --retry-delay 60 https://www.rultor.com
    mvn clean site-deploy -Prultor -Psite --errors --settings ../settings.xml --batch-mode
